// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDji5QNAZm5BPubwMxpw5VIPRCZutSFvPI',
    appId: '1:736850449294:web:aa00f29f34ee7b35938adf',
    messagingSenderId: '736850449294',
    projectId: 'steganalysispro-fb2d3',
    authDomain: 'steganalysispro-fb2d3.firebaseapp.com',
    storageBucket: 'steganalysispro-fb2d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJM_VF3WFB84AX4hjvfMk8NfFrryFv0yE',
    appId: '1:736850449294:android:add9aa57732451e6938adf',
    messagingSenderId: '736850449294',
    projectId: 'steganalysispro-fb2d3',
    storageBucket: 'steganalysispro-fb2d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMv3URS85IL576KRxFjMfWb_oObSs8vqM',
    appId: '1:736850449294:ios:6079ae8e01f96a9b938adf',
    messagingSenderId: '736850449294',
    projectId: 'steganalysispro-fb2d3',
    storageBucket: 'steganalysispro-fb2d3.appspot.com',
    iosBundleId: 'com.example.steganalysispro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMv3URS85IL576KRxFjMfWb_oObSs8vqM',
    appId: '1:736850449294:ios:4c9a1e8f25f996a0938adf',
    messagingSenderId: '736850449294',
    projectId: 'steganalysispro-fb2d3',
    storageBucket: 'steganalysispro-fb2d3.appspot.com',
    iosBundleId: 'com.example.steganalysispro.RunnerTests',
  );
}
